title: Mantle's Potato Bakery
tagline: >-
    Rong "Mantle" Bao's personal blog
email: webmaster@csmantle.top
description: >-
    A repository of my thoughts and ideas, organized and unorganized,
    up-to-date and outdated, and everything in between.
baseurl: "/"
url: https://csmantle.top
github_username: CSharperMantle
twitter_username: CSMantle3
rss: RSS feed
social:
  name: Rong Bao
  links:
    - https://github.com/CSharperMantle
    - https://twitter.com/CSMantle3
show_excerpts: true
permalink: date

collections:
  static:
    output: true
    permalink: /:path:output_ext

markdown: kramdown
theme: minima
plugins:
  - jekyll-postfiles
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji

sass:
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Extra URLs for reference in sitemap.xml
extra_urls:
  - url: /periotrisjs/
  - url: /la32r-instr-stats/
  - url: /ysyx-chip-area-visualizer/
