title: Mantle's Potato Bakery
tagline: >-
    Rong "Mantle" Bao's personal blog
email: baorong2005@126.com
description: >-
    A repository of my thoughts and ideas, organized and unorganized,
    up-to-date and outdated, and everything in between.
baseurl: "/"
url: "https://csmantle.top"
github_username: CSharperMantle
twitter_username: CSMantle3
social:
  name: Rong "Mantle" Bao
  links:
    - https://github.com/CSharperMantle
    - https://twitter.com/CSMantle3
show_excerpts: true

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
